name: github-page-deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown

      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check

      # - name: Install
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: install

      - name: Install
        uses: actions-rs/cargo@v1
        with:
          command: build --release

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.
